"""auto update

Revision ID: 96b33c363b1d
Revises: eee7c05de1c0
Create Date: 2026-09-11 18:00:51.778758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b33c363b1d'
down_revision: Union[str, Sequence[str], None] = 'eee7c05de1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('service_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'service_name')
    # ### end Alembic commands ###