"""auto update

Revision ID: a575e0b9f029
Revises: 96b33c363b1d
Create Date: 2026-09-11 22:40:57.992175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a575e0b9f029'
down_revision: Union[str, Sequence[str], None] = '96b33c363b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('tool_trace', sa.String(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_event_id'), 'agent_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.create_table('cmdb_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('dependencies', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmdb_assets_id'), 'cmdb_assets', ['id'], unique=False)
    op.create_table('oncall_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_window', sa.String(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=True),
    sa.Column('info_count', sa.Integer(), nullable=True),
    sa.Column('affected_systems', sa.String(), nullable=True),
    sa.Column('report_json', sa.String(), nullable=True),
    sa.Column('chatops_text', sa.String(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oncall_reports_id'), 'oncall_reports', ['id'], unique=False)
    op.create_index(op.f('ix_oncall_reports_session_id'), 'oncall_reports', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oncall_reports_session_id'), table_name='oncall_reports')
    op.drop_index(op.f('ix_oncall_reports_id'), table_name='oncall_reports')
    op.drop_table('oncall_reports')
    op.drop_index(op.f('ix_cmdb_assets_id'), table_name='cmdb_assets')
    op.drop_table('cmdb_assets')
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_event_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###