"""auto update

Revision ID: eee7c05de1c0
Revises: 
Create Date: 2026-09-11 17:40:19.931388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee7c05de1c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('applicant', sa.String(), nullable=False),
    sa.Column('applicant_role', sa.String(), nullable=True),
    sa.Column('biz_id', sa.String(), nullable=True),
    sa.Column('biz_type', sa.String(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_biz_id'), 'approval_requests', ['biz_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('acted_at', sa.String(), nullable=True),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('approver_role', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_steps_id'), 'approval_steps', ['id'], unique=False)
    op.create_index(op.f('ix_approval_steps_request_id'), 'approval_steps', ['request_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('after_json', sa.String(), nullable=True),
    sa.Column('before_json', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('ua', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_table('console_configs',
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_console_configs_id'), 'console_configs', ['id'], unique=False)
    op.create_table('events',
    sa.Column('ai_command', sa.String(), nullable=True),
    sa.Column('ai_output_json', sa.String(), nullable=True),
    sa.Column('ai_root_cause', sa.String(), nullable=True),
    sa.Column('ai_solution', sa.String(), nullable=True),
    sa.Column('candidates_json', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('degraded_reason', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rag_ms', sa.Float(), nullable=True),
    sa.Column('rag_score', sa.Float(), nullable=True),
    sa.Column('rag_status', sa.String(), nullable=True),
    sa.Column('raw_log', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('std_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('topology', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('kb_cases',
    sa.Column('alert_template', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('topology_snapshot', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_cases_case_id'), 'kb_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_kb_cases_id'), 'kb_cases', ['id'], unique=False)
    op.create_table('kb_change_sets',
    sa.Column('after_json', sa.String(), nullable=True),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('before_json', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('diff_json', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_change_sets_approval_request_id'), 'kb_change_sets', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_kb_change_sets_case_id'), 'kb_change_sets', ['case_id'], unique=False)
    op.create_index(op.f('ix_kb_change_sets_id'), 'kb_change_sets', ['id'], unique=False)
    op.create_table('kb_merge_proposals',
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_case_id', sa.String(), nullable=False),
    sa.Column('merged_case_ids', sa.String(), nullable=False),
    sa.Column('merge_strategy_json', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_merge_proposals_approval_request_id'), 'kb_merge_proposals', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_kb_merge_proposals_id'), 'kb_merge_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_kb_merge_proposals_master_case_id'), 'kb_merge_proposals', ['master_case_id'], unique=False)
    op.create_table('kb_versions',
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_json', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_versions_approval_id'), 'kb_versions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_kb_versions_case_id'), 'kb_versions', ['case_id'], unique=False)
    op.create_index(op.f('ix_kb_versions_id'), 'kb_versions', ['id'], unique=False)
    op.create_table('oidc_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_states_id'), 'oidc_states', ['id'], unique=False)
    op.create_index(op.f('ix_oidc_states_state'), 'oidc_states', ['state'], unique=True)
    op.create_table('rule_versions',
    sa.Column('change_note', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_id'), 'rule_versions', ['id'], unique=False)
    op.create_table('unknown_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_seen_service', sa.String(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('suggested_error_type', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unknown_templates_id'), 'unknown_templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_unknown_templates_id'), table_name='unknown_templates')
    op.drop_table('unknown_templates')
    op.drop_index(op.f('ix_rule_versions_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_oidc_states_state'), table_name='oidc_states')
    op.drop_index(op.f('ix_oidc_states_id'), table_name='oidc_states')
    op.drop_table('oidc_states')
    op.drop_index(op.f('ix_kb_versions_id'), table_name='kb_versions')
    op.drop_index(op.f('ix_kb_versions_case_id'), table_name='kb_versions')
    op.drop_index(op.f('ix_kb_versions_approval_id'), table_name='kb_versions')
    op.drop_table('kb_versions')
    op.drop_index(op.f('ix_kb_merge_proposals_master_case_id'), table_name='kb_merge_proposals')
    op.drop_index(op.f('ix_kb_merge_proposals_id'), table_name='kb_merge_proposals')
    op.drop_index(op.f('ix_kb_merge_proposals_approval_request_id'), table_name='kb_merge_proposals')
    op.drop_table('kb_merge_proposals')
    op.drop_index(op.f('ix_kb_change_sets_id'), table_name='kb_change_sets')
    op.drop_index(op.f('ix_kb_change_sets_case_id'), table_name='kb_change_sets')
    op.drop_index(op.f('ix_kb_change_sets_approval_request_id'), table_name='kb_change_sets')
    op.drop_table('kb_change_sets')
    op.drop_index(op.f('ix_kb_cases_id'), table_name='kb_cases')
    op.drop_index(op.f('ix_kb_cases_case_id'), table_name='kb_cases')
    op.drop_table('kb_cases')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_console_configs_id'), table_name='console_configs')
    op.drop_table('console_configs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_steps_request_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_biz_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###